spec:
  name: irlobby
  services:
    - name: web
      dockerfile_path: ./Dockerfile
      http_port: ${PORT}
      routes:
        - path: /
      health_check:
        http_path: /api/health
      envs:
        - key: NODE_ENV
          value: production
        - key: PGSSLMODE
          value: require