# Generated by Django 5.2.6 on 2025-09-18
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
    ]
