# Generated by Django 4.2.30 on 2026-07-21 19:57

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_ticketing"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="location_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="platform_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["buyer"], name="activities__buyer_i_071614_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["activity", "status"], name="activities__activit_bb7da5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["stripe_payment_intent_id"], name="activities__stripe__f70708_idx"
            ),
        ),
    ]
