# Generated by Django 4.2.30 on 2026-05-06 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activity_location_point_gist'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='activity_loc_point_gist',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='activities__stripe__f70708_idx',
            old_name='activities_t_stripe__idx',
        ),
        migrations.AlterField(
            model_name='activity',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['buyer'], name='activities__buyer_i_071614_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['activity', 'status'], name='activities__activit_bb7da5_idx'),
        ),
    ]
