# Generated by Django 4.2.30 on 2026-09-29 03:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


VERIFIED_CHURCHES = (
    "Franconia Mennonite Church",
    "Souderton Mennonite Church",
    "Blooming Glen Mennonite Church",
    "Plains Mennonite Church",
    "Zion Mennonite Church",
    "Perkasie Mennonite Church",
    "Deep Run Mennonite Church East",
    "Finland Mennonite Church",
)


def seed_verified_churches(apps, schema_editor):
    Church = apps.get_model("activities", "Church")
    for name in VERIFIED_CHURCHES:
        Church.objects.get_or_create(name=name, defaults={"is_verified": True})


def unseed_verified_churches(apps, schema_editor):
    Church = apps.get_model("activities", "Church")
    Church.objects.filter(name__in=VERIFIED_CHURCHES, is_verified=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0009_remove_activity_activity_loc_point_gist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('stripe_connect_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_connect_payouts_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='age_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='age_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='audience_gender',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('men', 'Men'), ('women', 'Women')], default='everyone', max_length=16),
        ),
        migrations.AddField(
            model_name='activity',
            name='calendar_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='donation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='host_kind',
            field=models.CharField(choices=[('person', 'Person'), ('church', 'Church')], default='person', max_length=16),
        ),
        migrations.AddField(
            model_name='activity',
            name='list_on_church_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='suggested_donation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='activityparticipant',
            name='include_self',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.CreateModel(
            name='HouseholdDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_photos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='activities.activity')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('stripe_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='activities.activity')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_activities', to='activities.church'),
        ),
        migrations.AddField(
            model_name='activityparticipant',
            name='dependents',
            field=models.ManyToManyField(blank=True, related_name='rsvps', to='activities.householddependent'),
        ),
        migrations.RunPython(seed_verified_churches, unseed_verified_churches),
    ]
