# Generated by Django 4.2.30 on 2026-09-29 03:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0009_remove_activity_activity_loc_point_gist_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
                ("stripe_account_id", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="event_photos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("stripe_session_id", models.CharField(blank=True, default="", max_length=255)),
                ("stripe_account_id", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HouseholdDependent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("date_of_birth", models.DateField()),
                ("sex", models.CharField(blank=True, default="", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date_of_birth", "id"],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="age_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="age_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="audience_gender",
            field=models.CharField(
                choices=[("everyone", "Everyone"), ("men", "Men"), ("women", "Women")],
                default="everyone",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="calendar_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="donation_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="host_kind",
            field=models.CharField(
                choices=[("person", "Person"), ("church", "Church")],
                default="person",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="list_on_church_calendar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="suggested_donation",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="include_self",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="platform_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["list_on_church_calendar", "calendar_approved"],
                name="activity_church_calendar_idx",
            ),
        ),
        migrations.AddField(
            model_name="householddependent",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="household_dependents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts",
                to="activities.activity",
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="giver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventphoto",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="activities.activity",
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="churches_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="host_church",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hosted_activities",
                to="activities.church",
            ),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="dependents",
            field=models.ManyToManyField(
                blank=True, related_name="rsvps", to="activities.householddependent"
            ),
        ),
        migrations.AddConstraint(
            model_name="church",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="unique_church_name_ci"
            ),
        ),
    ]
