# Generated by Django 4.2.30 on 2026-10-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0012_activity_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="householddependent",
            name="birth_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householddependent",
            name="birth_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householddependent",
            name="relationship",
            field=models.CharField(
                choices=[("spouse", "Spouse"), ("child", "Child")], default="child", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="householddependent",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
