# Generated by Django 4.2.30 on 2026-10-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0013_household_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="cancel_reason",
            field=models.CharField(blank=True, default="", max_length=280),
        ),
        migrations.AddField(
            model_name="activity",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
