# Generated by Django 4.2.30 on 2026-10-02 14:16

from django.db import migrations, models
from django.db.models import Q


def clear_legacy_requires_approval(apps, schema_editor):
    """`requires_approval` was a stored toggle that did nothing until now.

    Church-hosted and public-calendar gatherings can never require approval, so clear
    any leftover flag there before it starts gating RSVPs.
    """
    Activity = apps.get_model("activities", "Activity")
    Activity.objects.filter(requires_approval=True).filter(
        Q(host_kind="church") | Q(list_on_church_calendar=True, calendar_approved=True)
    ).update(requires_approval=False)


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0014_activity_cancellation"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="allow_rerequest",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="decline_reason",
            field=models.CharField(blank=True, default="", max_length=280),
        ),
        migrations.RunPython(clear_legacy_requires_approval, migrations.RunPython.noop),
    ]
