# Generated by Django 4.2.30 on 2026-10-02 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0015_activity_require_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventphoto",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_event_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
