"""
Django settings for irlobby_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
import environ
import sentry_sdk
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
env.read_env(BASE_DIR / ".env")
config = env


def parse_origin_list(value):
    return [item.strip() for item in value.split(",") if item.strip()]


def validate_origin_list(setting_name, origins, *, require_https):
    invalid_origins = []
    placeholder_origins = []

    for origin in origins:
        parsed = urlparse(origin)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            invalid_origins.append(origin)
            continue
        if require_https and parsed.scheme != "https":
            invalid_origins.append(origin)
        if any(placeholder in origin for placeholder in ["your-domain.com", "your-frontend-domain.com"]):
            placeholder_origins.append(origin)

    if invalid_origins:
        raise ImproperlyConfigured(
            f"{setting_name} contains invalid production origins: {', '.join(invalid_origins)}"
        )
    if placeholder_origins:
        raise ImproperlyConfigured(
            f"{setting_name} contains placeholder production origins: {', '.join(placeholder_origins)}"
        )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1", "testserver"],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django.contrib.sites",
    "corsheaders",
    "waffle",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.twitter",
    "channels",
    "users",
    "activities",
    "moderation",
    "swipes",
    "matches",
    "chat",
    "reviews",
]

AUTH_USER_MODEL = "users.User"

# Django AllAuth settings
SITE_ID = 1
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
SOCIALACCOUNT_AUTO_SIGNUP = True

# Twitter OAuth settings
TWITTER_CLIENT_ID = config("TWITTER_CLIENT_ID", default="")
TWITTER_CLIENT_SECRET = config("TWITTER_CLIENT_SECRET", default="")

# Social Account Providers
SOCIALACCOUNT_PROVIDERS = {
    "twitter": {
        "APP": {
            "client_id": config("TWITTER_CLIENT_ID", default=""),
            "secret": config("TWITTER_CLIENT_SECRET", default=""),
            "key": "",
        }
    }
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_RATES": {
        "auth_anon": "10/min",
        "auth_user": "30/min",
        "ticket_ops": "20/min",
        "swipe_ops": config("SWIPE_THROTTLE_RATE", default="120/hour"),
        "match_reads": config("MATCH_THROTTLE_RATE", default="240/hour"),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=60),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=7),
}

REFRESH_TOKEN_COOKIE_NAME = "refresh_token"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "waffle.middleware.WaffleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "irlobby_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "irlobby_backend.wsgi.application"

ASGI_APPLICATION = "irlobby_backend.asgi.application"

REDIS_URL = config("REDIS_URL", default="redis://localhost:6379/0")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# dj_database_url imported earlier to avoid module-level import error

# Disable persistent DB connections during test runs to avoid stale-cursor
# errors with pytest-django + postgis (cursor reused across transactions).
_IS_TESTING = (
    "pytest" in sys.modules
    or "test" in sys.argv
    or os.environ.get("PYTEST_CURRENT_TEST") is not None
)

DATABASES = {
    "default": dj_database_url.config(
        default=config("DATABASE_URL", default="sqlite:///db.sqlite3"),
        engine="django.contrib.gis.db.backends.postgis",
        conn_max_age=600,
        conn_health_checks=True,
    )
}

if _IS_TESTING:
    # Server-side cursors interact badly with pytest-django transaction
    # wrapping (cursor handle becomes invalid across transactions).
    DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True
    options = DATABASES["default"].setdefault("OPTIONS", {})
    options["application_name"] = "pytest"

# CORS settings
# Read allowed origins from environment to support dynamic deploy domains.
raw_cors_origins = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174,http://localhost:3000,http://127.0.0.1:3000,https://your-frontend-domain.com",
)
CORS_ALLOWED_ORIGINS = parse_origin_list(raw_cors_origins)

raw_csrf_origins = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:5173,http://127.0.0.1:5173,https://your-frontend-domain.com",
)
CSRF_TRUSTED_ORIGINS = parse_origin_list(raw_csrf_origins)

raw_websocket_origins = config("WEBSOCKET_ALLOWED_ORIGINS", default=raw_cors_origins)
WEBSOCKET_ALLOWED_ORIGINS = parse_origin_list(raw_websocket_origins)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False  # Use CORS_ALLOWED_ORIGINS list in production

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-forwarded-proto",
    "x-forwarded-host",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

WAFFLE_FLAG_DEFAULT = False

if not DEBUG and not _IS_TESTING:
    if not CORS_ALLOWED_ORIGINS or not CSRF_TRUSTED_ORIGINS or not WEBSOCKET_ALLOWED_ORIGINS:
        raise ImproperlyConfigured(
            "CORS_ALLOWED_ORIGINS, CSRF_TRUSTED_ORIGINS, and WEBSOCKET_ALLOWED_ORIGINS must be set in production."
        )
    validate_origin_list("CORS_ALLOWED_ORIGINS", CORS_ALLOWED_ORIGINS, require_https=True)
    validate_origin_list("CSRF_TRUSTED_ORIGINS", CSRF_TRUSTED_ORIGINS, require_https=True)
    validate_origin_list(
        "WEBSOCKET_ALLOWED_ORIGINS", WEBSOCKET_ALLOWED_ORIGINS, require_https=True
    )
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=SECURE_SSL_REDIRECT, cast=bool)
    CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=SECURE_SSL_REDIRECT, cast=bool)
    default_samesite = "None" if SECURE_SSL_REDIRECT else "Lax"
    SESSION_COOKIE_SAMESITE = config("SESSION_COOKIE_SAMESITE", default=default_samesite)
    CSRF_COOKIE_SAMESITE = config("CSRF_COOKIE_SAMESITE", default=default_samesite)
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True, cast=bool
    )
    SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=True, cast=bool)
    SECURE_REFERRER_POLICY = config("SECURE_REFERRER_POLICY", default="same-origin")
    SECURE_CONTENT_TYPE_NOSNIFF = True
else:
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default=REDIS_URL)
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default=REDIS_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
if _IS_TESTING:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True

CELERY_BEAT_SCHEDULE = {
    "run-matchmaking": {
        "task": "matches.tasks.run_matchmaking",
        "schedule": 60.0,
    },
    "notify-upcoming-activities": {
        "task": "activities.tasks.notify_upcoming_activities",
        "schedule": 300.0,
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email settings
# Email configuration
# In development we default to the console backend so that password reset emails
# are printed to the terminal rather than requiring a real SMTP server.  The
# frontend will still receive a usable reset URL because `FRONTEND_BASE_URL` is
# set to the local web dev server by default.
if DEBUG:
    EMAIL_BACKEND = config(
        "EMAIL_BACKEND",
        default="django.core.mail.backends.console.EmailBackend",
    )
else:
    EMAIL_BACKEND = config(
        "EMAIL_BACKEND",
        default="django.core.mail.backends.smtp.EmailBackend",
    )

EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="no-reply@irlobby.local")

EXPO_PUSH_API_URL = config("EXPO_PUSH_API_URL", default="https://exp.host/--/api/v2/push/send")
EXPO_PUSH_ACCESS_TOKEN = config("EXPO_PUSH_ACCESS_TOKEN", default="")

# Frontend base URL for password reset links
FRONTEND_BASE_URL = config("FRONTEND_BASE_URL", default="http://localhost:5173/")

SENTRY_DSN = config("SENTRY_DSN", default="")
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        traces_sample_rate=config("SENTRY_TRACES_SAMPLE_RATE", default=0.1, cast=float),
        profiles_sample_rate=config("SENTRY_PROFILES_SAMPLE_RATE", default=0.1, cast=float),
        environment=config("SENTRY_ENVIRONMENT", default="production"),
    )

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.core.mail": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}

STRIPE_API_KEY = config("STRIPE_API_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_SUCCESS_URL = config("STRIPE_SUCCESS_URL", default="http://localhost:3000/tickets/success")
STRIPE_CANCEL_URL = config("STRIPE_CANCEL_URL", default="http://localhost:3000/tickets/cancel")
ENABLE_TICKETING = config("ENABLE_TICKETING", default=True, cast=bool)
