# Generated by Django 4.2.30 on 2026-05-06 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abusereport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='blockeduser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abusereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=10),
        ),
    ]
