# Generated by Django 4.2.30 on 2026-10-02 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moderation", "0002_alter_abusereport_options_alter_blockeduser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abusereport",
            name="target_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="abusereport",
            name="target_snapshot",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="abusereport",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("chat_message", "Gathering chat message"),
                    ("direct_message", "1:1 message"),
                    ("event_photo", "Gathering photo"),
                    ("activity", "Gathering"),
                    ("join_request", "Request to join"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="abusereport",
            name="reported_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="abuse_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
