# Generated by Django 4.2.30 on 2026-10-02 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moderation", "0003_abusereport_content_targets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abusereport",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filed_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
