import { MD3DarkTheme, MD3LightTheme, type MD3Theme } from 'react-native-paper';

import {
  brand as brandTokens,
  fontSize as fontSizeTokens,
  lineHeight as lineHeightTokens,
  motion as motionTokens,
  palette,
  radii as radiiTokens,
  shadows as shadowsTokens,
  spacing as spacingTokens,
  typography as typographyTokens,
} from './tokens';

export {
  palette,
  brandTokens as brand,
  fontSizeTokens as fontSize,
  lineHeightTokens as lineHeight,
  motionTokens as motion,
};

export const appColors = {
  primary: palette.primary,
  primaryDeep: palette.primaryDeep,
  primarySoft: palette.primarySoft,
  primaryGlow: palette.primaryGlow,
  secondary: palette.secondary,
  secondaryDeep: palette.secondaryDeep,
  secondarySoft: palette.secondarySoft,
  accent: palette.accent,
  accentDeep: palette.accentDeep,
  accentSoft: palette.accentSoft,
  success: palette.success,
  warning: palette.warning,
  danger: palette.danger,
  ink: palette.ink,
  mutedInk: palette.mutedInk,
  softInk: palette.softInk,
  line: palette.line,
  lineStrong: palette.lineStrong,
  card: palette.surface,
  cardStrong: palette.surfaceMuted,
  background: palette.background,
  backgroundAccent: palette.primarySoft,
  overlay: palette.overlay,
  white: palette.white,
  black: palette.black,
  darkBackground: palette.darkBackground,
  darkCard: palette.darkSurface,
  darkLine: palette.darkLine,
  darkMutedInk: palette.darkMutedInk,
} as const;

export const radii = radiiTokens;
export const spacing = spacingTokens;
export const shadows = shadowsTokens;

export const appTypography = {
  heading: typographyTokens.heading,
  headingDisplay: typographyTokens.headingDisplay,
  bodyRegular: typographyTokens.bodyRegular,
  bodyMedium: typographyTokens.bodyMedium,
  bodySemibold: typographyTokens.bodySemibold,
  display: typographyTokens.display,
} as const;

export const lightTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: radiiTokens.md,
  colors: {
    ...MD3LightTheme.colors,
    primary: palette.primary,
    onPrimary: palette.white,
    primaryContainer: palette.primarySoft,
    onPrimaryContainer: palette.primaryDeep,
    secondary: palette.secondary,
    onSecondary: palette.ink,
    secondaryContainer: palette.secondarySoft,
    onSecondaryContainer: palette.secondaryDeep,
    tertiary: palette.accent,
    onTertiary: palette.ink,
    tertiaryContainer: palette.accentSoft,
    onTertiaryContainer: palette.accentDeep,
    error: palette.danger,
    background: palette.background,
    onBackground: palette.ink,
    surface: palette.surface,
    onSurface: palette.ink,
    surfaceVariant: palette.surfaceMuted,
    onSurfaceVariant: palette.mutedInk,
    outline: palette.line,
    outlineVariant: palette.lineStrong,
    shadow: palette.ink,
    scrim: palette.overlay,
    inverseSurface: palette.ink,
    inverseOnSurface: palette.white,
    inversePrimary: palette.primaryGlow,
    elevation: {
      level0: 'transparent',
      level1: palette.surface,
      level2: palette.surfaceMuted,
      level3: palette.surfaceMuted,
      level4: palette.surfaceMuted,
      level5: palette.surfaceMuted,
    },
  },
};

export const darkTheme: MD3Theme = {
  ...MD3DarkTheme,
  roundness: radiiTokens.md,
  colors: {
    ...MD3DarkTheme.colors,
    primary: palette.primaryGlow,
    onPrimary: palette.darkBackground,
    primaryContainer: palette.primaryDeep,
    onPrimaryContainer: palette.primarySoft,
    secondary: palette.secondary,
    onSecondary: palette.darkBackground,
    secondaryContainer: palette.secondaryDeep,
    onSecondaryContainer: palette.secondarySoft,
    tertiary: palette.accent,
    onTertiary: palette.darkBackground,
    tertiaryContainer: palette.accentDeep,
    onTertiaryContainer: palette.accentSoft,
    error: palette.danger,
    background: palette.darkBackground,
    onBackground: palette.darkInk,
    surface: palette.darkSurface,
    onSurface: palette.darkInk,
    surfaceVariant: palette.darkSurfaceMuted,
    onSurfaceVariant: palette.darkMutedInk,
    outline: palette.darkLine,
    outlineVariant: palette.darkLine,
    shadow: palette.black,
    scrim: palette.black,
    inverseSurface: palette.darkInk,
    inverseOnSurface: palette.darkBackground,
    inversePrimary: palette.primary,
    elevation: {
      level0: 'transparent',
      level1: palette.darkSurface,
      level2: palette.darkSurfaceMuted,
      level3: palette.darkSurfaceMuted,
      level4: palette.darkSurfaceMuted,
      level5: palette.darkSurfaceMuted,
    },
  },
};
