# Generated by Django 4.2.30 on 2026-10-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_normalize_match_order"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                condition=models.Q(("activity__isnull", True)),
                fields=("user_a", "user_b"),
                name="unique_direct_match_per_pair",
            ),
        ),
    ]
