# Generated by Django 5.2.6 on 2025-09-23 02:31

from django.db import migrations
from django.db.models import Count


def cleanup_duplicate_emails(apps, schema_editor):
    User = apps.get_model('users', 'User')
    
    # Find emails that appear more than once
    duplicate_emails = User.objects.values('email').annotate(
        email_count=Count('email')
    ).filter(email_count__gt=1).values_list('email', flat=True)
    
    for email in duplicate_emails:
        # Get all users with this email
        users_with_email = User.objects.filter(email=email).order_by('-last_login', '-date_joined')
        
        # Keep the first user (most recent login/join date)
        user_to_keep = users_with_email.first()
        
        # Delete the rest
        users_to_delete = users_with_email.exclude(id=user_to_keep.id)
        count_deleted = users_to_delete.count()
        
        if count_deleted > 0:
            users_to_delete.delete()
            print(f"Cleaned up {count_deleted} duplicate users for email: {email}")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_oauth_id_user_oauth_provider'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_emails, reverse_code=migrations.RunPython.noop),
    ]
