# Generated by Django 4.2.30 on 2026-07-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_social_auth_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_connect_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_connect_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
