# Generated by Django 4.2.30 on 2026-09-29 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0010_foyer_gatherings"),
        ("users", "0011_stripe_connect_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="church",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="activities.church",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
