# Generated by Django 4.2.30 on 2026-10-01 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_foyer_gatherings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dm_from_shared_events",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("only_me", "Only me"),
                    ("friends", "Friends"),
                    ("church", "My church"),
                    ("public", "Public"),
                ],
                default="only_me",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_phone",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                fields=("requester", "recipient"), name="unique_friendship_direction"
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                django.db.models.functions.comparison.Least("requester", "recipient"),
                django.db.models.functions.comparison.Greatest("requester", "recipient"),
                name="unique_friendship_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.CheckConstraint(
                check=models.Q(("requester", models.F("recipient")), _negated=True),
                name="friendship_not_self",
            ),
        ),
    ]
