# Generated by Django 4.2.30 on 2026-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_social_profile_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privacy_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
