# Generated by Django 4.2.30 on 2026-10-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_terms_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialauthidentity",
            name="apple_refresh_token",
            field=models.TextField(blank=True, default=""),
        ),
    ]
