# Generated by Django 4.2.30 on 2026-10-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_socialauthidentity_apple_refresh_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_birthday",
            field=models.BooleanField(default=False),
        ),
    ]
