# Generated by Django 4.2.30 on 2026-10-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_show_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday_audience",
            field=models.CharField(
                choices=[
                    ("only_me", "Only me"),
                    ("friends", "Friends"),
                    ("church", "My church"),
                    ("public", "Public"),
                ],
                default="friends",
                max_length=10,
            ),
        ),
    ]
